export const EXPENSE_MY_LIST_REQUEST = 'EXPENSE_MY_LIST_REQUEST';
export const EXPENSE_MY_LIST_SUCCESS = 'EXPENSE_MY_LIST_SUCCESS';
export const EXPENSE_MY_LIST_FAIL = 'EXPENSE_MY_LIST_FAIL';

export const CREATE_NEW_EXPENSE_REQUEST = 'CREATE_NEW_EXPENSE_REQUEST';
export const CREATE_NEW_EXPENSE_SUCCESS = 'CREATE_NEW_EXPENSE_SUCCESS';
export const CREATE_NEW_EXPENSE_FAIL = 'CREATE_NEW_EXPENSE_FAIL';
export const CREATE_NEW_EXPENSE_RESET = 'CREATE_NEW_EXPENSE_RESET';
