export const EXPENSE_MY_LIST_REQUEST = 'EXPENSE_MY_LIST_REQUEST';
export const EXPENSE_MY_LIST_SUCCESS = 'EXPENSE_MY_LIST_SUCCESS';
export const EXPENSE_MY_LIST_FAIL = 'EXPENSE_MY_LIST_FAIL';

export const CREATE_NEW_EXPENSE_REQUEST = 'CREATE_NEW_EXPENSE_REQUEST';
export const CREATE_NEW_EXPENSE_SUCCESS = 'CREATE_NEW_EXPENSE_SUCCESS';
export const CREATE_NEW_EXPENSE_FAIL = 'CREATE_NEW_EXPENSE_FAIL';
export const CREATE_NEW_EXPENSE_RESET = 'CREATE_NEW_EXPENSE_RESET';

export const EXPENSE_BY_ID_REQUEST = 'EXPENSE_BY_ID_REQUEST';
export const EXPENSE_BY_ID_SUCCESS = 'EXPENSE_BY_ID_SUCCESS';
export const EXPENSE_BY_ID_FAIL = 'EXPENSE_BY_ID_FAIL';
export const EXPENSE_BY_ID_RESET = 'EXPENSE_BY_ID_RESET';

export const ADD_EXPENSE_TO_LIST_REQUEST = 'ADD_EXPENSE_TO_LIST_REQUEST';
export const ADD_EXPENSE_TO_LIST_SUCCESS = 'ADD_EXPENSE_TO_LIST_SUCCESS';
export const ADD_EXPENSE_TO_LIST_FAIL = 'ADD_EXPENSE_TO_LIST_FAIL';
export const ADD_EXPENSE_TO_LIST_RESET = 'ADD_EXPENSE_TO_LIST_RESET';
